#!/usr/bin/env bash

VERSION="2.2"

DIR="$( cd "$( dirname "$0" )" && pwd )"

case "$1" in

	'') echo -e "\n ArchImage CLI requires an argument, run -h for more info.\n"
		;;
	
	--help|-h) 
		echo -e "\n ArchImage CLI v$VERSION \n\n A command line interface to build AppImages based on JuNest, the lightweight\n Arch Linux based distro that runs, without root privileges, on top of any\n other Linux distro."
		echo -e "\n USAGE:\n\n   archimage-cli [OPTION]\n   archimage-cli [OPTION] [PROGRAM]\n"
		echo -e " OPTIONS:\n\n   -h,--help		Shows this message.\n   -v,--version		Shows the version.\n   -b,--build		Create the script to build the AppImage.\n   -s,--sync		Update archimage-cli to the latest version."
		echo -e "\n SITES: \n\n   - https://github.com/IVAN-HC	\n\n   - https://github.com/IVAN-HC/ARCHIMAGE	\n\n   - https://github.com/FSQUILLACE/JUNEST\n"
		;;

	--version|-v) echo "ArchImage CLI v$VERSION"
		;;
	
	--build|-b)
		while [ -n "$1" ]; do
		cd $(xdg-user-dir DESKTOP)
		case "$2" in
			'') echo -e "\n USAGE:	archimage-cli -b [PROGRAM]\n"
			exit;;
			*)
			wget -q https://raw.githubusercontent.com/ivan-hc/ArchImage/main/sample-next-junest.sh -O $2-junest.sh
			sed -i "s#APP=SAMPLE#APP=$2#g" $2-junest.sh
			echo -e "\n---------------------------------------------------------------------------\n"
			read -r -ep '◆ NAME THE MAIN EXECUTABLE IN "$PATH", OR LEAVE BLANK IF IT IS THE SAME: ' response
    			case $response in
    				'');;
				*) 
				mv ./$2-junest.sh ./$2-junest.sh.old
				sed -n '1,4p' ./$2-junest.sh.old >> ./$2-junest.sh
				echo 'BIN="'$response'"' >> ./$2-junest.sh
				sed -n '6,20000000p' ./$2-junest.sh.old >> ./$2-junest.sh
				rm -f ./$2-junest.sh.old;;
			esac
			echo -e "\n---------------------------------------------------------------------------\n"
			read -r -ep "◆ ADD DEPENDENCES, OR LEAVE BLANK: " RESPONSE
    			case $RESPONSE in
				*) 
				mv ./$2-junest.sh ./$2-junest.sh.old
				sed -n '1,5p' ./$2-junest.sh.old >> ./$2-junest.sh
				echo 'DEPENDENCES="'$RESPONSE'"' >> ./$2-junest.sh
				sed -n '7,20000000p' ./$2-junest.sh.old >> ./$2-junest.sh
				rm -f ./$2-junest.sh.old;;
			esac
			echo -e "\n---------------------------------------------------------------------------\n"
			read -p "◆ DO YOU WANT TO ENABLE CHAOTIC-AUR (y,N)? " yn
    			case $yn in
				[Yy]* ) sed -i 's/###//g' ./$2-junest.sh;;
				[Nn]*|* ) ;;
			esac
			echo -e "\n---------------------------------------------------------------------------\n"
			read -p "◆ DO YOU WANT TO INCLUDE BINUTILS AND GZIP (y,N)? " yn
    			case $yn in
				[Yy]* ) sed -i 's/#BASICSTUFF/BASICSTUFF/g' ./$2-junest.sh;;
				[Nn]*|* ) ;;
			esac
			echo -e "\n---------------------------------------------------------------------------\n"
			read -p "◆ DO YOU WANT TO INCLUDE THE BASE-DEVEL PACKAGE TO COMPILE FROM AUR (y,N)? " yn
    			case $yn in
				[Yy]* ) sed -i 's/#COMPILERS/COMPILERS/g' ./$2-junest.sh;;
				[Nn]*|* ) ;;
			esac
			echo -e "\n---------------------------------------------------------------------------\n"
			echo -e '◆ All of the following steps are intended for advanced users and aim to\n  lighten the final AppImage archive. Always press ENTER if you are unsure.'
			read -p "  DO YOU WANT TO REMOVE FILES IN /usr/bin AND SPECIFY WHAT TO SAVE (y,N)? " yn
    			case $yn in
				[Yy]* ) sed -i 's/#_savebins/_savebins/g' ./$2-junest.sh
					echo -e "\n---------------------------------------------------------------------------\n"
					read -r -ep "◆ LIST BINARIES TO SAVE BEYOND THE ONE SPECIFIED ABOVE OR LEAVE BLANK $(echo -e '\n  DO NOT ADD ASTERISKS, THEY ARE ALREADY PROVIDED IN THE SCRIPT\n:') " savebins
					case "$savebins" in
					'');;
					*) 
					sed -i "s/SAVEBINSPLEASE/$savebins/g" ./$2-junest.sh;;
					esac;;
				[Nn]*|* ) ;;
			esac
			chmod a+x ./$2-junest.sh
			echo -e "\n---------------------------------------------------------------------------\n"
			echo -e '◆ Attempt to lighten the final AppImage by removing unnecessary folders.'
			read -p "  DO YOU WANT TO REMOVE FOLDERS IN /usr/share AND SPECIFY WHAT TO SAVE (y,N)? " yn
    			case $yn in
				[Yy]* ) sed -i 's/#_saveshare/_saveshare/g' ./$2-junest.sh
					echo -e "\n---------------------------------------------------------------------------\n"
					read -r -ep "◆ LIST FOLDERS TO SAVE OR LEAVE BLANK$(echo -e '\n  DO NOT ADD ASTERISKS, THEY ARE ALREADY PROVIDED IN THE SCRIPT\n:') " saveshare
					case "$saveshare" in
					'');;
					*) 
					sed -i "s/SAVESHAREPLEASE/$saveshare/g" ./$2-junest.sh;;
					esac;;
				[Nn]*|* ) ;;
			esac
			echo -e "\n---------------------------------------------------------------------------\n"
			echo -e '◆ The next step will take account of the folders in /usr/share that you have\n  saved previously to automatically check libraries in /usr/lib that contain\n  the keyword. If a file is missing the app may not work. Note that this step\n  will use "readelf" and "find" to locate files directly dependent on the\n  main executables saved in /usr/bin, the related libraries and the libraries\n  related to these. The process could be much longer than normal.'
			read -p "  DO YOU WANT TO LET THE SCRIPT DECIDE WHICH LIBRARIES TO SAVE (y,N)? " yn
    			case $yn in
				[Yy]* ) sed -i 's/#_binlibs/_binlibs/g' ./$2-junest.sh
					sed -i 's/#_liblibs/_liblibs/g' ./$2-junest.sh
					sed -i 's/#_mvlibs/_mvlibs/g' ./$2-junest.sh
					echo -e "\n---------------------------------------------------------------------------\n"
					read -p "◆ DO YOU WANT TO INCLUDE THE /usr/lib/dri/swrast_dri.so DRIVER (y,N)? " yn
    					case $yn in
						[Yy]* ) sed -i 's/#_include_swrast_dri/_include_swrast_dri/g' ./$2-junest.sh;;
						[Nn]*|* ) ;;
					esac
					echo -e "\n---------------------------------------------------------------------------\n"
					read -p "◆ DO YOU WANT TO INCLUDE EXTRA ITEMS OF YOUR CHOICE IN /usr/lib (y,N)? " yn
    					case $yn in
						[Yy]* ) 
							echo -e "\n---------------------------------------------------------------------------\n"
							sed -i 's/#_libkeywords/_libkeywords/g' ./$2-junest.sh
							read -r -ep "◆ LIST KEYWORDS TO SEARCH AND SAVE IN /usr/lib OR LEAVE BLANK $(echo -e '\n  DO NOT ADD ASTERISKS, THEY ARE ALREADY PROVIDED IN THE SCRIPT\n:') " savelibs
							case "$savelibs" in
							'');;
							*) 
								sed -i "s/SAVELIBSPLEASE/$savelibs/g" ./$2-junest.sh
								echo -e "\n---------------------------------------------------------------------------\n"
								read -r -ep "◆ DO YOU WISH TO ADD KEIWORDS IN /usr/lib TO ENABLE THE AUDIO (y,N)?" yn
								case $yn in
								[Yy]* ) sed -i 's/LIBSAVED="/LIBSAVED="alsa jack pipewire pulse /g' ./$2-junest.sh
									echo -e "\n---------------------------------------------------------------------------\n"
									read -r -ep "◆ I RECOMMEND TO USE CA-CERTIFICATES TO ENABLE THE INTERNET $(echo -e '\n  DO YOU WISH TO ADD IT INTO THE SCIPT (y,N)?') " yn
									case $yn in
										[Yy]* ) sed -i 's/DEPENDENCES="/DEPENDENCES="ca-certificates /g'  ./$2-junest.sh
											sed -i 's/BINSAVED="/BINSAVED="certificates /g'  ./$2-junest.sh
											sed -i 's/#_binlibs/_binlibs/g' ./$2-junest.sh
											sed -i 's/SHARESAVED="/SHARESAVED="certificates /g'  ./$2-junest.sh
											sed -i 's/#_saveshare/_saveshare/g' ./$2-junest.sh
											sed -i 's/LIBSAVED="/LIBSAVED="certificates /g'  ./$2-junest.sh
											sed -i 's/#_mvlibs/_mvlibs/g' ./$2-junest.sh
											sed -i 's/#_liblibs/_liblibs/g' ./$2-junest.sh;;
										[Nn]*|* ) ;;
									esac;;
								[Nn]*|* ) ;;
								esac;;
							esac;;
						[Nn]*|* ) ;;
					esac;;
				[Nn]*|* ) ;;
			esac
			chmod a+x ./$2-junest.sh
			echo -e "\n---------------------------------------------------------------------------\n"
			chmod a+x ./$2-junest.sh
			echo -e " THE SCRIPT IS READY, RUN IT TO CREATE AN APPIMAGE! \n"
			echo -e "\n SUGGESTIONS:\n\n - from line titled 'REMOVE SOME BLOATWARES', add a list of items to be\n   deleted to avoid an excess in the size of the final AppImage archive.\n"
			exit
			;;
		esac
		done
		;;
		
	--sync|-s) 
		cd $DIR
		echo -ne " Synchronizing $(./archimage-cli -v)...\r"; sleep 0.5
  		wget -q https://raw.githubusercontent.com/ivan-hc/ArchImage/main/archimage-cli -O ~/.cache/archimage-cli && chmod a+x ~/.cache/archimage-cli;
  		mv ~/.cache/archimage-cli ./archimage-cli; echo "  ArchImage version $VERSION is updated! "
  		;;
  		
  		*)
  		echo -e "\n Unknown option '$1', run -h for more info.\n"
  		;;
	
esac
